# Generated by Django 6.0.6 on 2026-06-21 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('event_type', models.CharField(choices=[('Holiday', 'Holiday'), ('Event', 'Event'), ('Exam', 'Exam'), ('Emergency', 'Emergency'), ('Notice', 'Notice')], default='Event', max_length=20)),
            ],
        ),
    ]
