# Generated by Django 6.0.6 on 2026-06-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0005_studentprofile_city_studentprofile_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='cover_banner',
            field=models.ImageField(blank=True, null=True, upload_to='cover_banners/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
