# Generated by Django 6.0.6 on 2026-06-23 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0006_studentprofile_cover_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycontent',
            name='rich_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DayAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_accessed_at', models.DateTimeField(auto_now_add=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadmap.dailycontent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='roadmap.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'day')},
            },
        ),
    ]
