# Generated by Django 6.0.6 on 2026-06-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0007_dailycontent_rich_content_dayaccesslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Handwritten', 'Handwritten Notes'), ('Python', 'Python'), ('Java', 'Java'), ('C++', 'C++'), ('DSA', 'Data Structures & Algorithms'), ('System Design', 'System Design'), ('Other', 'Other')], default='Other', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='notes/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
