# Generated by Django 6.0.6 on 2026-06-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0008_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycontent',
            name='aptitude_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailycontent',
            name='core_subject_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailycontent',
            name='dsa_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailycontent',
            name='web_dev_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
