# Generated by Django 6.0.6 on 2026-06-26 16:51

from django.db import migrations

def migrate_rich_content(apps, schema_editor):
    DailyContent = apps.get_model('roadmap', 'DailyContent')
    for day in DailyContent.objects.all():
        if day.rich_content and not day.dsa_content:
            day.dsa_content = day.rich_content
            day.save()

class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0009_dailycontent_aptitude_content_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_rich_content),
    ]
