# Generated by Django 6.0.6 on 2026-06-26 17:24

from django.db import migrations, models


def set_existing_progress_true(apps, schema_editor):
    ProgressTracker = apps.get_model('roadmap', 'ProgressTracker')
    ProgressTracker.objects.all().update(
        dsa_completed=True,
        aptitude_completed=True,
        core_completed=True,
        web_dev_completed=True
    )

class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0010_auto_20260626_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresstracker',
            name='aptitude_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progresstracker',
            name='core_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progresstracker',
            name='dsa_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progresstracker',
            name='web_dev_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_existing_progress_true, reverse_code=migrations.RunPython.noop),
    ]
